// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQ9z0ZvwC3gKYnpPiN0bsKfnn79ZL8MY',
    appId: '1:217591306657:web:19cd7be04294a8b8af53e0',
    messagingSenderId: '217591306657',
    projectId: 'classwork9mobileapp',
    authDomain: 'classwork9mobileapp.firebaseapp.com',
    storageBucket: 'classwork9mobileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuO1dr_XJL_S4BRiduWVVdvt1CX4Cz0wY',
    appId: '1:217591306657:ios:b565d91dc4687529af53e0',
    messagingSenderId: '217591306657',
    projectId: 'classwork9mobileapp',
    storageBucket: 'classwork9mobileapp.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuO1dr_XJL_S4BRiduWVVdvt1CX4Cz0wY',
    appId: '1:217591306657:ios:37a170fcd4d4107caf53e0',
    messagingSenderId: '217591306657',
    projectId: 'classwork9mobileapp',
    storageBucket: 'classwork9mobileapp.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
